### ISSUE TITLE
Date in quoted replies

### ISSUE THREAD

**Issue by infertux** [ioerror/torbirdy#23]
Thanks for this great plugin. However, I don't quite understand why the date of the original message is stripped of the reply:
- Default Thunderbird config:

> On 07/03/15 01:31, John Doe wrote:
> [message]
- With TorBirdy:

> John Doe:
> [message]

I find that having this timestamp is very useful, especially for long-running threads. What is the reason for not including it?

TorBirdy sets `mailnews.reply_header_type` to `1` instead of `2` which is the [default in Thunderbird](http://kb.mozillazine.org/Reply_header_settings).

**Comment by azadi** [comment]
Two reasons:

1. To hide your time zone from the person you are replying to because the timestamp from the email you are replying is converted to your local time. The person you are replying to can then determine your timezone from the reply.
2. To hide the language (locale) of Thunderbird since that is revealed in the "John Doe wrote:", which will be different for different locales.

While I understand that this may not be convenient or required for all users, this is a preference that TorBirdy will not allow you to change -- if you change it using `about:config`, TorBirdy will override it when Thunderbird restarts. [This](https://trac.torproject.org/projects/tor/wiki/torbirdy#BeforeusingTorBirdy) explains the design decision for enforcing preferences.

If you really want to get rid of it, you can clone the TorBirdy repository, remove lines 156-158 in `components/torbirdy.js` and then create your own XPI (run `make make-xpi` in the directory root).

**Comment by infertux** [comment]
1. I thought TorBirdy was forcing UTC by default? At least, there is a flag in the settings that reads _Do not set Thunderbird's time zone to UTC [default: set to UTC]_. In any case, I think privacy-concious people have set up their OS to use UTC because their timezone would be leaked by many other programs (Git, etc.) using the system's timezone.

2. Good point. Maybe TorBirdy could override Thunderbird to always use the English phrase `On [date], [author] wrote:` regardless of the system's locale? I *think* it's what `mailnews.reply_header_authorwrote` is for. Or maybe add a new checkbox in TorBirdy settings for this? What do you reckon?

Anyway, I'm happy to make my own fork if you reckon the current design decisions make more sense - just wanted to discuss what were the reasons behind these choices :)

**Comment by azadi** [comment]
1. Yes, we do set to UTC, but we don't want to force users to change their system TZ. (While I agree with what you said, it would be an inconvenience for many users to do this.)  Also, good news is that @arthuredelstein from Tor Project submitted patches upstream that have randomized the headers and easily allow us to set the timezone without changing it for everything else. More details in the upcoming release!

2. Sounds like a good idea but we decided on "X:" because it just seemed easier. Anyways, I am open to the idea of making the "On [date], [author] wrote:" format optional.
