### ISSUE TITLE
Exclude some accounts

### ISSUE THREAD

**Issue by FacundoAcevedo** [ioerror/torbirdy#29]
Hi, I have some accounts that i need to connect directly to internet instead by tor, is it possible configure?

Greets!

**Comment by azadi** [comment]
Hi,

Unfortunately this is not possible because some preferences cannot be isolated on a per-account basis. There are two things you can do:

1). Use multiple profiles. In one profile you can have TorBirdy installed and enabled, while in the other you can use your account that you don't want to go over Tor. 

2). Use [Transparent Torification](https://trac.torproject.org/projects/tor/wiki/torbirdy/preferences#a-TransparentTorification). Which means that all other TorBirdy privacy settings will remain intact but traffic will be sent in the clear and **not** over Tor.

This has also been discussed before so you can go over the tickets for more information: https://trac.torproject.org/projects/tor/ticket/8487, specifically the first comment.

**Comment by FacundoAcevedo** [comment]
Great, I've used the 1st option, it's working fantastic. tnx!

**Comment by azadi** [comment]
Good to know! Closing this ticket.
